"use node";

/**
 * Agent Objecteur — Gestion des Réponses & Objections
 *
 * Analyzes prospect replies semantically via LLM Anthropic and categorizes them:
 * - trop_cher: price objection
 * - besoin_reflexion: needs time to think
 * - question_technique: technical question
 * - interet_confirme: confirmed interest → lead becomes "hot"
 * - refus: refusal → lead becomes "archived"
 *
 * For objections (trop_cher, besoin_reflexion, question_technique),
 * generates a suggested counter-response and submits it to HITL validation.
 *
 * This file uses "use node" because it depends on the Vercel AI SDK which
 * requires Node.js. It can ONLY export actions (internalAction).
 * Queries and mutations are in objectorHelpers.ts.
 *
 * Requirements: 10.1, 10.2, 10.3, 10.4, 10.5, 10.6
 */

import { anthropic } from "@ai-sdk/anthropic";
import { generateText, Output } from "ai";
import { v } from "convex/values";
import { z } from "zod";
import { internal } from "../_generated/api";
import { internalAction } from "../_generated/server";

// ─── Zod schemas for LLM structured output ──────────────────────────────────

/**
 * Reply categorization result from the LLM.
 */
export const ReplyCategorySchema = z.enum([
  "trop_cher",
  "besoin_reflexion",
  "question_technique",
  "interet_confirme",
  "refus",
]);

export type ReplyCategory = z.infer<typeof ReplyCategorySchema>;

/**
 * Full analysis result including category and reasoning.
 */
export const ReplyAnalysisSchema = z.object({
  category: ReplyCategorySchema.describe(
    "The category of the prospect's reply: trop_cher (too expensive), besoin_reflexion (needs time to think), question_technique (technical question), interet_confirme (confirmed interest), refus (refusal)",
  ),
  reasoning: z
    .string()
    .describe("Brief explanation of why this category was chosen"),
  sentiment: z
    .enum(["positive", "neutral", "negative"])
    .describe("Overall sentiment of the reply"),
});

export type ReplyAnalysis = z.infer<typeof ReplyAnalysisSchema>;

/**
 * Counter-response generated by the LLM for objection handling.
 */
export const CounterResponseSchema = z.object({
  subject: z
    .string()
    .describe("Email subject line for the counter-response — concise and empathetic"),
  body: z
    .string()
    .describe("Full counter-response body — addresses the objection directly, provides value"),
  tone: z
    .enum(["expert", "support", "tech"])
    .describe("Tone used for the counter-response"),
});

export type CounterResponse = z.infer<typeof CounterResponseSchema>;

// ─── Categories that require a counter-response ─────────────────────────────

const OBJECTION_CATEGORIES: ReadonlySet<ReplyCategory> = new Set([
  "trop_cher",
  "besoin_reflexion",
  "question_technique",
]);

// ─── Build the analysis prompt ──────────────────────────────────────────────

/**
 * Build the system and user prompts for reply categorization.
 */
export function buildAnalysisPrompt(
  replyContent: string,
  originalMessage: string | undefined,
  product: { name: string; uspDescription?: string } | undefined,
  promptTemplate?: string,
): { system: string; user: string } {
  const productContext = product
    ? `Product: ${product.name}\nUSP: ${product.uspDescription ?? "N/A"}`
    : "Product: Unknown";

  const system = promptTemplate
    ? promptTemplate
    : `You are an expert sales analyst for a SaaS company. Your job is to analyze prospect replies and categorize them accurately.

${productContext}

CATEGORIES:
- trop_cher: The prospect mentions price, cost, budget constraints, or finds the offer too expensive
- besoin_reflexion: The prospect needs time to think, wants to discuss internally, or asks to follow up later
- question_technique: The prospect asks technical questions about features, integrations, compatibility, or implementation
- interet_confirme: The prospect expresses clear interest, wants to proceed, asks about next steps, or requests a demo/trial
- refus: The prospect clearly declines, says they're not interested, already have a solution, or asks to stop contact

RULES:
- Analyze the semantic meaning, not just keywords
- Consider the overall tone and intent of the message
- If ambiguous, lean toward the most actionable category
- Be precise in your reasoning`;

  const originalContext = originalMessage
    ? `\n\nOriginal message sent to the prospect:\n"""${originalMessage}"""`
    : "";

  const user = `Analyze this prospect reply and categorize it:${originalContext}

Prospect's reply:
"""${replyContent}"""

Categorize this reply and explain your reasoning.`;

  return { system, user };
}

// ─── Build the counter-response prompt ──────────────────────────────────────

/**
 * Build the system and user prompts for counter-response generation.
 */
export function buildCounterResponsePrompt(
  replyContent: string,
  category: ReplyCategory,
  originalMessage: string | undefined,
  product: { name: string; uspDescription?: string; landingPageBaseUrl: string } | undefined,
  leadContext: {
    name?: string;
    enrichmentData?: {
      company?: string;
      role?: string;
    };
  },
): { system: string; user: string } {
  const productContext = product
    ? `Product: ${product.name}\nUSP: ${product.uspDescription ?? "N/A"}\nLanding Page: ${product.landingPageBaseUrl}`
    : "Product: Unknown";

  const categoryInstructions: Record<string, string> = {
    trop_cher:
      "The prospect finds the price too high. Address the value proposition, ROI, and consider mentioning flexible pricing or a trial period. Do NOT lower the price — focus on value.",
    besoin_reflexion:
      "The prospect needs time to think. Be understanding, provide a helpful resource or case study, and suggest a specific follow-up date. Keep the door open without being pushy.",
    question_technique:
      "The prospect has technical questions. Provide clear, accurate answers. If you don't have specific technical details, offer to connect them with the technical team. Be precise and helpful.",
  };

  const system = `You are a skilled sales professional handling objections for a SaaS product. Your goal is to write a thoughtful, empathetic counter-response that addresses the prospect's concern.

${productContext}

OBJECTION TYPE: ${category}
${categoryInstructions[category] ?? "Address the prospect's concern directly."}

RULES:
- Write a natural, human message — NO templates, NO generic phrases
- Be empathetic and understanding of the prospect's position
- Provide concrete value in your response
- Keep the message concise (100-200 words for email body)
- The subject line should acknowledge the concern (under 60 chars)
- Do NOT use placeholder brackets like [Name] — use actual data or omit
- Write in the same language as the prospect's reply`;

  const leadInfo = leadContext.name ? `Prospect name: ${leadContext.name}` : "";
  const companyInfo = leadContext.enrichmentData?.company
    ? `Company: ${leadContext.enrichmentData.company}`
    : "";
  const roleInfo = leadContext.enrichmentData?.role
    ? `Role: ${leadContext.enrichmentData.role}`
    : "";

  const user = `Generate a counter-response for this objection:

${leadInfo}
${companyInfo}
${roleInfo}

Original message sent:
"""${originalMessage ?? "N/A"}"""

Prospect's reply (category: ${category}):
"""${replyContent}"""

Write a counter-response that addresses their concern and moves the conversation forward.`;

  return { system, user };
}

// ─── Main Action: Analyze Reply ─────────────────────────────────────────────

/**
 * Analyze a prospect's reply semantically and take appropriate action.
 *
 * Pipeline:
 * 1. Read the message and lead from DB
 * 2. Load product config and prompt_config
 * 3. Call Anthropic LLM for semantic categorization (structured output)
 * 4. Update message with reply category
 * 5. Update lead status based on category:
 *    - interet_confirme → hot
 *    - refus → archived
 *    - trop_cher/besoin_reflexion/question_technique → pending
 * 6. If objection category → generate counter-response via LLM
 * 7. Submit counter-response to HITL validation pipeline
 * 8. On LLM error → log and preserve current state
 *
 * Requirements: 10.1, 10.2, 10.3, 10.4, 10.5, 10.6
 */
export const analyzeReply = internalAction({
  args: {
    messageId: v.id("messages"),
    replyContent: v.string(),
  },
  returns: v.null(),
  handler: async (ctx, { messageId, replyContent }) => {
    // 1. Read the message from DB
    const message = await ctx.runQuery(
      internal.agents.objectorHelpers.getMessageForAnalysis,
      { messageId },
    );

    if (!message) {
      await ctx.runMutation(internal.logs.createLog, {
        agentType: "objector",
        level: "warn",
        message: `Analysis skipped: message ${messageId} not found.`,
        messageId,
      });
      return null;
    }

    // 2. Read the lead
    const lead = await ctx.runQuery(
      internal.agents.objectorHelpers.getLeadById,
      { leadId: message.leadId },
    );

    if (!lead) {
      await ctx.runMutation(internal.logs.createLog, {
        agentType: "objector",
        level: "warn",
        message: `Analysis skipped: lead for message ${messageId} not found.`,
        messageId,
      });
      return null;
    }

    // 3. Load product config (if lead has a productId)
    let product = null;
    if (lead.productId) {
      product = await ctx.runQuery(
        internal.agents.objectorHelpers.getProductBySlug,
        { slug: lead.productId },
      );
    }

    // 4. Load objector prompt_config
    const promptConfig = await ctx.runQuery(
      internal.agents.objectorHelpers.getObjectorPromptConfig,
      { productId: lead.productId ?? undefined },
    );

    // 5. Call Anthropic LLM for semantic categorization
    try {
      const { system, user } = buildAnalysisPrompt(
        replyContent,
        message.suggestedReply ?? message.finalContent ?? undefined,
        product
          ? {
              name: product.name,
              uspDescription: product.uspDescription ?? undefined,
            }
          : undefined,
        promptConfig?.promptTemplate ?? undefined,
      );

      const { output: analysis } = await generateText({
        model: anthropic("claude-sonnet-4-20250514"),
        output: Output.object({
          schema: ReplyAnalysisSchema,
        }),
        system,
        prompt: user,
      });

      const category = analysis.category;

      // 6. Update message category and lead status
      await ctx.runMutation(
        internal.agents.objectorHelpers.updateReplyAnalysis,
        {
          messageId,
          leadId: message.leadId,
          replyCategory: category,
        },
      );

      await ctx.runMutation(internal.logs.createLog, {
        agentType: "objector",
        level: "info",
        message: `Reply analyzed for message ${messageId}: category="${category}", sentiment="${analysis.sentiment}". Lead status updated.`,
        leadId: message.leadId,
        messageId,
        metadata: {
          category,
          sentiment: analysis.sentiment,
          reasoning: analysis.reasoning,
        },
      });

      // 7. If objection category → generate counter-response
      if (OBJECTION_CATEGORIES.has(category)) {
        try {
          const { system: counterSystem, user: counterUser } =
            buildCounterResponsePrompt(
              replyContent,
              category,
              message.suggestedReply ?? message.finalContent ?? undefined,
              product
                ? {
                    name: product.name,
                    uspDescription: product.uspDescription ?? undefined,
                    landingPageBaseUrl: product.landingPageBaseUrl,
                  }
                : undefined,
              {
                name: lead.name ?? undefined,
                enrichmentData: lead.enrichmentData ?? undefined,
              },
            );

          const { output: counterResponse } = await generateText({
            model: anthropic("claude-sonnet-4-20250514"),
            output: Output.object({
              schema: CounterResponseSchema,
            }),
            system: counterSystem,
            prompt: counterUser,
          });

          // 8. Submit counter-response to HITL validation pipeline
          const counterMessageId = await ctx.runMutation(
            internal.agents.objectorHelpers.insertCounterResponse,
            {
              leadId: message.leadId,
              suggestedReply: counterResponse.body,
              subject: counterResponse.subject,
              tone: counterResponse.tone,
              contextualLink: product?.landingPageBaseUrl ?? undefined,
              originalMessageId: messageId,
            },
          );

          await ctx.runMutation(internal.logs.createLog, {
            agentType: "objector",
            level: "info",
            message: `Counter-response generated for message ${messageId} → new message ${counterMessageId} (category: ${category}). Submitted to HITL validation.`,
            leadId: message.leadId,
            messageId: counterMessageId,
            metadata: {
              originalMessageId: messageId,
              objectionCategory: category,
              counterTone: counterResponse.tone,
            },
          });
        } catch (counterError) {
          // Counter-response generation failure is non-critical
          // The categorization and status update already succeeded
          await ctx.runMutation(internal.logs.createLog, {
            agentType: "objector",
            level: "warn",
            message: `Counter-response generation failed for message ${messageId}: ${
              counterError instanceof Error
                ? counterError.message
                : String(counterError)
            }. Categorization succeeded but no counter-response was created.`,
            leadId: message.leadId,
            messageId,
            metadata: {
              category,
              errorType:
                counterError instanceof Error
                  ? counterError.constructor.name
                  : "unknown",
            },
          });
        }
      }
    } catch (llmError) {
      // LLM analysis failure — log and preserve current state
      await ctx.runMutation(internal.logs.createLog, {
        agentType: "objector",
        level: "error",
        message: `LLM analysis failed for message ${messageId}: ${
          llmError instanceof Error ? llmError.message : String(llmError)
        }. Reply not categorized.`,
        leadId: message.leadId,
        messageId,
        metadata: {
          errorType:
            llmError instanceof Error
              ? llmError.constructor.name
              : "unknown",
          errorMessage:
            llmError instanceof Error ? llmError.message : String(llmError),
        },
      });
    }

    return null;
  },
});
